# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QLSU
                                 A QGIS plugin
 This plugin allows linear spectral unmixing of multispectral remote sensing data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-14
        copyright            : (C) 2022 by Bahadir Celik
        email                : bahadircelik@osmaniye.edu.tr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QLSU class from file QLSU.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qlsu import QLSU
    return QLSU(iface)
